### ISSUE TITLE
(Issue) Hoarder Bugs did not spawn with default config settings on Assurance

### ISSUE THREAD

**Issue by KaiCollins1** [Azim/HoarderBud#1]
Currently testing different configurations of HoarderBud on LAN mode. I have landed on Assurance and March with the default configuration file, and the first time I landed on Assurance, there were zero hoarder bugs on the entire map, and I stayed in the facility for the entire day. 

I have not had this issue since, so I have no idea what caused it. I did not see anything strange in the logs when starting up Lethal either. Just bringing it to attention in case something is found later down the road relating to this.

Here is my plugin folder for other mods I currently have installed, and I also have the required hookgenpatcher in the respective folder.
![image](https://github.com/Azim/HoarderBud/assets/98558519/cb3f37b0-2b9c-4c06-ad84-4fe013e6307e)

**Comment by Azim** [comment]
If you happen to reproduce it again, please attach a OutputLog.log from the BepInEx folder.
I heard of this happening to someone else as well but never managed to reproduce yet

**Comment by Azim** [comment]
Solving as stale
