### ISSUE TITLE
(Issue) Config file mislabelled

### ISSUE THREAD

**Issue by KaiCollins1** [Azim/HoarderBud#2]
The config file that was generated by the mod is currently labelled as being 1.0.9. Not very important, but something to be fixed in the next version.

![image](https://github.com/Azim/HoarderBud/assets/98558519/601d4457-054b-4064-9afc-b51b089906f4)

**Comment by Azim** [comment]
yeah i updated the version in manifest but forgotten the version in the assembly, it will also incorrectly say the version in bepinex console and logs.

i will try to not forget to update it with the next version haha but noone really looks at that anyway
