### ISSUE TITLE
(Issue) Improper physics on hoarder bug egg appendages

### ISSUE THREAD

**Issue by KaiCollins1** [Azim/HoarderBud#3]
I was playing around with the hoarder bug eggs, and the appendages on the bug inside the egg seemed to be very floaty when the player moves with a certain amount of speed, or jumps.

**Comment by KaiCollins1** [comment]
https://github.com/Azim/HoarderBud/assets/98558519/196af1fa-67f3-4347-a1f5-08d3d26daeaf

**Comment by Azim** [comment]
Thats just how the original ones behave, i simply instantiate a dummy bug with no AI for each egg item.
idk how to fix, so leaving it as is
