### ISSUE TITLE
(Issue) Hoarder bug egg hitbox allows it to be unrecoverable when thrown at a door

### ISSUE THREAD

**Issue by KaiCollins1** [Azim/HoarderBud#4]
The small hitbox of the egg item allows it to be entirely within the "interact-box" of the main door. This may happen with other items, but is easier with an egg as it can be thrown at the door.

![Screenshot 2024-01-12 144802](https://github.com/Azim/HoarderBud/assets/98558519/d6c0d921-8429-43b2-9083-23049859fcff)

![Screenshot 2024-01-12 144750](https://github.com/Azim/HoarderBud/assets/98558519/0e0286d4-f98a-4c44-a867-a003d899dd01)

**Comment by Azim** [comment]
the throwing code is planned for a complete rewrite (currently uses flashbang code).
rn its effectively teleportation with inbetween animation,  which is why throwing it upward doesnt work.
I wanna make it into a proper rigidbidy with actual physics interactions instead of raycasting

**Comment by Azim** [comment]
which could fix this issue as well but we will see when we get there. Not gonna specifically change that for now

**Comment by KaiCollins1** [comment]
Interesting to know how throwing works. I honestly forgot flashbangs existed.
