### ISSUE TITLE
(Idea/Suggestion) Config option to allow hoarder bug eggs to function outside.

### ISSUE THREAD

**Issue by KaiCollins1** [Azim/HoarderBud#5]
If inside mobs are capable of spawning outside (idk if there are limitations), it would be interesting to allow hoarder bugs to spawn outside with a config. There is not much use other than to mess around with friends.

**Comment by Azim** [comment]
Because most AI breaks when outside, i do a check on if LethalEscape mod is present to determine if it can spawn outside.
So by installing Lethal Escape you will be able to enable eggs hatching outside

**Comment by KaiCollins1** [comment]
Awesome!
