### ISSUE TITLE
HoarderBug + Scarlet devil mansion bug

### ISSUE THREAD

**Issue by TheRealMrKam** [Azim/HoarderBud#6]
Just letting you know there is an issue between your mod and Scarlet devil mansion, that makes fail the generation of the interior, wierd error.

ps: Nothing to do with the error but... also wanted to ask can you make it so we can choose if only the ones we hatch from the egg are friendly ?

**Comment by Azim** [comment]
would appreciate the game log with the error

**Comment by Azim** [comment]
> can you make it so we can choose if only the ones we hatch from the egg are friendly 

good idea, i will add this to the list

**Comment by TheRealMrKam** [comment]
I'll reproduce when i have time and send it to you !

But as i remember the log says nothing about hoarderbud , it says scarlet mansion has failed to load and bunch of other things like interiors failed as well because of an harmony error.

 I narrowed it down to hoarderbud by testing all my mods one by one with the mansion mod.

**Comment by TheRealMrKam** [comment]
Here is the log  !
[LogOutput.log](https://github.com/Azim/HoarderBud/files/14230920/LogOutput.log)
Not much hoarderbud side but mansion exploded !
Wierd bug haha

**Comment by Azim** [comment]
> Here is the log ! [LogOutput.log](https://github.com/Azim/HoarderBud/files/14230920/LogOutput.log) Not much hoarderbud side but mansion exploded ! Wierd bug haha

Happens when both my and their mod attempt to edit SpawnScrapInLevel method.
Unfortunately, there isnt much i could do about that

**Comment by TheRealMrKam** [comment]
Oh so is the modder of the scarlet masion able to do something ?

**Comment by Azim** [comment]
I took a glance at their mod but im still not sure what they are using it for. Some sort of loot multiplier? with more precise transpiler instructions or different approach they can work around that.
I use it for "spawn only gifts" option, maybe i could move it into a separate mod but im not sure if i should or want to do that

**Comment by TheRealMrKam** [comment]
I see, could you make it in a way that if we disable the  gift option on your mod, that method isn't called, so it doesn't interfere, is it possible ? 

Mods for gifts do exist too : https://thunderstore.io/c/lethal-company/p/Zehs/OnlyPresents/

**Comment by Azim** [comment]
Since a mod which adds that functionality already exists, i can just remove that feature
