### ISSUE TITLE
[Suggestion] Would it be possible to make Hoarder Bugs friendly but only attack you if you attack them, or take their stuff.

### ISSUE THREAD

**Issue by haroelim** [Azim/HoarderBud#7]
To my understand, in the vanilla code, Hoarder bugs attack either because you attacked them, took their stuff, or because you stood too close to them for too long.

Would it be possible so that you can stand next to them as long as you want, and they only attack you if you attack them or take their stuff?

**Comment by Azim** [comment]
ai logic is complicated and doing any more than what im doing right now would require to basically rewrite entirety of their ai, which im not a fan of

**Comment by haroelim** [comment]
Oh darn, thanks anyways. I like the concept of the bugs bringing the loot to the front, but I still want the loot bugs to be a bit of a threat, although I've had some players complain that the bugs attack them too often.
