### ISSUE TITLE
Doesn't work well with Lethal Escape?

### ISSUE THREAD

**Issue by Xherdos** [Azim/HoarderBud#8]
Since Thunderstore doesn't have a Comment Section...

I wanted to hint out that this Mod appearently doesn't work well with LethalEscape by XCeezy.

The HoarderBugs spawned by this Mod teleports outside of the Facility the second the egg lands on the ground. (They gather inside or around the ship)

p.s Sometimes For some reason when the Ground is a grid the Eggs fall through the walkable ground into the abyss.

**Comment by Xherdos** [comment]
Yea nvm. Sorry for creating this Issue just saw that i can deactivate it over the Config File at LethalEscape. Though the Eggs falling through the Grid can happen.

**Comment by Azim** [comment]
Eggs failing through the grid is a base game bug, which can also happen to flashbang or other "throwables"

> Yea nvm. Sorry for creating this Issue just saw that i can deactivate it over the Config File at LethalEscape. Though the Eggs falling through the Grid can happen.

**Comment by Azim** [comment]
i actually do an explicit LethalEscape check to allow egg hatching while "outside"
