### ISSUE TITLE
No Inside Enemies Spawned?

### ISSUE THREAD

**Issue by albertus-96** [Azim/HoarderBud#9]
![image](https://github.com/Azim/HoarderBud/assets/85718909/4545057a-fe84-4855-93a4-2adc010c1755)

I played on V50. As attached, I already set the value to false, but no inside enemies appear beside hoaderbud. The outside enemies appear normal, only the inside enemies that didn't appear properly.  
Is this a bug or do I need to set something else?

**Comment by Azim** [comment]
Please send full game log

**Comment by albertus-96** [comment]
Hey, here my full game log
[LogOutput.log](https://github.com/Azim/HoarderBud/files/14998705/LogOutput.log)

**Comment by Azim** [comment]
Yep seems like ill need some updating to do for v50

**Comment by NeatWolf** [comment]
yup, same issue here, got an error on boomboxpatches - it basically breaks every spawn in the game :(
I miss these little cute critters, could you pretty please patch it? Can't live without my Yuppies, it's not the same game anymore  T_T

If you're going to update it - is there any chance you could set a configurable chance [0..1] that a specific Yuppie spawns as a normal enemy? I believe even at 0.05 would keep people on their toes :D

**Comment by Azim** [comment]
That sounds like a fun feature, but not sure how easy it is to add, i will take a look. Probably wont have the time to work on any of this until weekend, unfortunately

**Comment by albertus-96** [comment]
> Yep seems like ill need some updating to do for v50

Ah thank you, I thought I didn't properly installed it. Thank you for the answer. Great work man!

**Comment by NeatWolf** [comment]
> That sounds like a fun feature, but not sure how easy it is to add, i will take a look. Probably wont have the time to work on any of this until weekend, unfortunately

No pressure, and I appreciate you spending your free time for the community and to revive those pesky happy critters ^^
Even having just the little buddies fixed would be great - I assume something about the boombox broke - and I didn't even realize it was a feature ^^
Besides, I can see plenty of Youtubers installing the mod if not all of them were friendly (the random chance on spawn I mentioned above) - a surprise attack makes good content. 
Yet I understand that would need testing, and proper host/client replication. more of a wishlist thing :)

**Comment by Azim** [comment]
After further testing, i couldnt reproduce the issue

> ![image](https://private-user-images.githubusercontent.com/85718909/322834824-4545057a-fe84-4855-93a4-2adc010c1755.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MjYyMjgsIm5iZiI6MTcxMzcyNTkyOCwicGF0aCI6Ii84NTcxODkwOS8zMjI4MzQ4MjQtNDU0NTA1N2EtZmU4NC00ODU1LTkzYTQtMmFkYzAxMGMxNzU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDE4NTg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYzFlNTFjMDdjNmExODVhMzYxODI3YTZjMGM4NzQ2OWE1NDZhYjllZDQ2MGY2Nzk4NThjMjFiYTI0ZWMzN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6feDRqZ3gtYzAUd0VLdMMwHTVJRr6B0jSlubgrtvuRU)
> 
> I played on V50. As attached, I already set the value to false, but no inside enemies appear beside hoaderbud. The outside enemies appear normal, only the inside enemies that didn't appear properly. Is this a bug or do I need to set something else?

as enemies spawned properly for me. Didnt get the weird boombox error message either. I uploaded a testing build to the github releases page, rebuilt with latest game assemblies, try that just in case and let me know if anything changes

**Comment by Azim** [comment]
https://github.com/Azim/HoarderBud/releases/tag/v50

**Comment by dragontwosix** [comment]
> https://github.com/Azim/HoarderBud/releases/tag/v50

I was also having this problem - no inside enemies and boombox errors being spammed in console 

This v50 dll works for me  

Thanks!

**Comment by Azim** [comment]
> > https://github.com/Azim/HoarderBud/releases/tag/v50
> 
> I was also having this problem - no inside enemies and boombox errors being spammed in console
> 
> This v50 dll works for me
> 
> Thanks!

weird. ho well ig ill push out a proper update this evening then

**Comment by RedSun42** [comment]
Using Lethal quantity I'm also having all my enemy spawn rate to 0

**Comment by Azim** [comment]
> Using Lethal quantity I'm also having all my enemy spawn rate to 0

send logs

**Comment by albertus-96** [comment]
> https://github.com/Azim/HoarderBud/releases/tag/v50

Hey. apologies for my late reply. 

As pointed out by @dragontwosix, it also works for me.

Thank you.
